version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: ["5434:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    ports: ["6380:6379"]

  api:
    build: ./backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    command: uvicorn app.main:app --host 0.0.0.0 --port ${API_PORT} --reload
    volumes:
      - ./backend:/app

  worker:
    build: ./backend
    env_file: .env
    depends_on:
      - api
      - redis
    command: python -m app.worker

  web:
    build: ./frontend
    env_file: .env
    depends_on:
      - api
    ports: ["3000:3000"]
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    volumes:
      - ./frontend:/src/app

volumes:
  dbdata:
